# Quantum Circuit Simulator

Implementing a simple quantum circuit simulator.


Implemented functionalities of the circuit simulator:
 * initialize a state
 * read a program/circuit, and for each gate:
  * calculate the matrix operator
  * apply the operator (modify state)
 * perform multi-shot measurements of all qubits using the weighted random technique
 * can run variational quantum algorithms

In [38]:
import numpy as np
from numpy.random import choice

### Quantum Gates

#### Single qubit gates

In [27]:
# inverse of the square root of 2
isqrt2 = 1/np.sqrt(2)

x = np.array([
    [0, 1],
    [1, 0]
])

z = np.array([
    [1, 0],
    [0, -1]
])

h = np.array([
    [isqrt2, isqrt2],
    [isqrt2, -isqrt2],
])

#### Two-qubit gates

In [26]:
cx = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0],
])

sw = np.array([
    [1, 0, 0, 0],
    [0, 0, 1, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1],
])

#### Parametric gates

$ U_3(\theta, \phi, \lambda) = \begin{pmatrix}
    \cos\frac{\theta}{2} & -e^{i\lambda}\sin\frac{\theta}{2}  \\
    e^{i\phi}\sin\frac{\theta}{2} & e^{i\phi + i\lambda}\cos\frac{\theta}{2} 
  \end{pmatrix}$

In [4]:

def param_gates(euler_theta, euler_phi, euler_lambda):
    
    u3 = np.array([
        [np.cos(euler_theta/2), -np.e**(euler_lambda*1j) * np.sin(euler_theta/2)],
        [np.e**(euler_phi*1j) * np.sin(euler_theta/2), np.e**(euler_phi*1j + euler_lambda*1j) * np.cos(euler_theta/2)]
    ])
    
    return u3

Dictionary for defined unitary gates

In [28]:
unitary_gates = {"x": x, "z": z, "h": h, "cx": cx, "sw": sw}

### Computational basis vector states

In [29]:
# computational basis
basis_states = [ [1, 0], [0, 1] ]

# classical bit states as strings
cbits = ["0", "1"]

### Quantum Circuit Simulator parent class

Contains methods required for simulation.

In [72]:
class QCSimulator:
    def __init__(self, qubits_num, shots, params, qcirc):
        """Takes a quantum circuit program, qcirc. Creates initial state vector
        of qubits_num qubits.
        """
        
        # initializer
        self.qubits_num = qubits_num
        self.shots_num = shots
        self.params = params
        
        # create initial state vector of qubits_num qubits [1, 0, ... ]
        self.init_state = self.get_ground_state()
        print("Initial state:\t", self.init_state, "\n")
        
        # get number of gate operations to compute
        operations_num = len(qcirc)
        
        # circuit handler, read circuit, calculate matrix operator
        # multiply the state with the operator and return final state.
        self.final_state = self.circuit_handler(operations_num, qcirc)
        print("Final State vector:\n%s\n"%(self.final_state))
        
        # make measurements, get counts
        self.counts = self.get_counts(self.final_state)
        
        # Print out statistics results in a nice form
        self.print_counts(self.counts)
        
    
    def get_ground_state(self):
        """Initialize a quantum state.
        Returns a vector of size 2**qubits_num with all zeroes except
        the first element which is 1."""
        
        ground_state_base = np.array([1, 0])
        ground_state_qnum = ground_state_base
        for i in range(self.qubits_num - 1):
            ground_state_qnum = np.kron(ground_state_base, ground_state_qnum)
            
        return ground_state_qnum
    
    
    def print_counts(self, counts):
        """Print out nicely looking count results"""
        
        print("\nMeasurement results:\n{")
        for i in counts.keys():
            print('\t"{}":\t{},'.format(str(i), counts[i]))
        print("}\n")
    
    
    def get_operator(self, gate_unitary, qubits_target):
        """Returns a unitary operator of size 2**n x 2**n for a given
        quantum gate and target number of qubits.
        Resizing the gate's martix to the dimension of the state vector"""
        
        # if matrix shape ==  state shape, return matrix and exit
        if np.shape(gate_unitary) == (2**self.qubits_num, 2**self.qubits_num):
                return gate_unitary
        elif np.shape(gate_unitary) > (2**self.qubits_num, 2**self.qubits_num):
                return gate_unitary
        
        # define 2x2 identity matrix
        I = np.identity(2)
        
        # a list of the order of kronecker product operations
        kron_order = []
        
        # number of iterations for adding gates into list
        ops = 1 + ( (2**self.qubits_num)/2 / np.shape(gate_unitary)[0])
        for k in range(int(ops)):
            if k == qubits_target:
                kron_order.append(gate_unitary)
            else:
                kron_order.append(I)
                
        gate_unitary_new = kron_order[0]
                
        for i in range(self.qubits_num - 1):
            # check if operator size/shape is equal to 2**n x 2**n, where n = qubits_num
            if np.shape(gate_unitary_new) == (2**self.qubits_num, 2**self.qubits_num):
                return gate_unitary_new
            
            gate_unitary_new = np.kron(gate_unitary_new, kron_order[i+1])
            
        return gate_unitary_new
    
    
    def circuit_handler(self, operations_num, qcirc):
        """Handles quantum circuit input, managing operations with gates, operators
        and state vectors. Returns final state vector."""
        
        final_state = self.init_state
        
        for i in range(operations_num):
            gate_name = qcirc[i]["gate"]
            param_values = qcirc[i]["params"] if "params" in qcirc[i].keys() else {}
            target = qcirc[i]["target"]
            if len(target) == 1:
                target = target[0]
            elif len(target) == 2:
                target = target[1]
            
            if gate_name in unitary_gates.keys():
                gate = unitary_gates[gate_name]
            elif gate_name not in unitary_gates.keys():
                global_1 = {param_values["theta"]: self.params[0]}
                global_2 = {param_values["phi"]: self.params[1]}
                gate = param_gates(global_1["global_1"], global_2["global_2"], param_values["lambda"])
            else:
                print("\n[-] Error! Gate not yet defined\n")
                break
            
            # resize gates, find matrix operator if necessary
            gate = self.get_operator(gate, target)
            # print("%s-gate\n\b%s"%(gate_name.upper(), gate))
            
            # matrix vector multiplicaion operation
            try:
                final_state = np.dot(gate, final_state)
            except ValueError:
                print("\n[-] Error: Unitary gate shape: {} not aligned with state vector shape: {}\n".format(np.shape(gate), np.shape(final_state)))
                break
                
            print("Final state --> [%s-gate]:\n%s\n"%(gate_name.upper(), final_state))
            
        return final_state      
    
    
    def get_counts(self, state_vector):
        """Execute measurements in a loop shots_num times and returns a dictionary object
        with statistics in the form:
        {
            element_index: number_of_occurrences,
            ...
        }
        only from elements which occurred - returned from measrements."""
        
        # find list of all possible quantum states
        qstates = basis_states
        cstates = cbits
        for i in range(self.qubits_num - 1):
            qstates = [ list(np.kron(j, k)) for j in basis_states for k in qstates ]
            cstates = [ j + k for j in cbits for k in cstates ]
        
        # fill in probabilities of each quantum state
        prob_states = []
        for i in range( len(qstates) ):
            p = np.dot( qstates[i], state_vector )
            pp = np.dot(p, np.conj(p)) 
            prob_states.append( pp.real )

        print("Weighted probabilitites:\n{}".format(prob_states))
        
        # loop measurement using weighted random technique
        # dictionary to hold statistics of states and their counts
        counts = {}
        for i in range( self.shots_num ):
            collapsed_state = choice( cstates, 1, p=prob_states )
            if collapsed_state[0] in counts:
                counts[collapsed_state[0]] += 1
            elif not collapsed_state[0] in counts:
                counts[collapsed_state[0]] = 1
        
        print("beofre ocunat", counts)
        return counts

#### Example class for running variational quantum algorithms

In [73]:
class VQE(QCSimulator):
    def __init__(self, N, shots_num, params, circuit):
        QCSimulator.__init__(self, N, shots, params, circuit)
        
        # counts = self.counts
        
        # create a random probability vector
        np.random.seed(999999)
        self.target_state = np.random.rand(2**N)
        # normalize the vector to get a valid probability vector
        self.target_state /= sum(self.target_state)
        print(self.target_state)
        
        # ...calculate cost here....
        print("cost:", self.objective_function())
        
        # minimize
        # minimum = minimize(cost, params, method="Powell", tol=1e-6)
        
    
    def objective_function(self):
        """An objective function that takes in as input a list of the variational form's parameters.
        Returns the cost associated with those parameters"""
        
        self.final_state = [i / 1024 for i in self.counts.values()]
        cost = sum( [np.abs(self.final_state[i] -  self.target_state[i]) for i in range(2**N)] )
        return cost

# Prepare VQE circuit here
N = 2
shots = 1024
params = np.array([np.pi, np.pi/2])
circuit = [
    {"gate": "h", "target": [0]},
    {"gate": "h", "target": [1]},
    #{"gate": "cx", "target": [0, 1]},
    #{"gate": "u3", "params": {"theta": "global_1", "phi": "global_2", "lambda": -np.pi}, "target": [0]},
    #{"gate": "u3", "params": {"theta": "global_1", "phi": "global_2", "lambda": -np.pi}, "target": [1]},
    #{"gate": "cx", "target": [1, 0]},
]
# Run VQE algorithm via the quantum circuit simulator
VQE(N, shots, params, circuit)

Initial state:	 [1 0 0 0] 

Final state --> [H-gate]:
[0.70710678 0.         0.70710678 0.        ]

Final state --> [H-gate]:
[0.5 0.5 0.5 0.5]

Final State vector:
[0.5 0.5 0.5 0.5]

Weighted probabilitites:
[0.2499999999999999, 0.2499999999999999, 0.2499999999999999, 0.2499999999999999]
beofre ocunat {'10': 270, '00': 270, '11': 242, '01': 242}

Measurement results:
{
	"10":	270,
	"00":	270,
	"11":	242,
	"01":	242,
}

[0.22027533 0.20863466 0.51316198 0.05792803]
cost: 0.553667712711295
